package com.rijaldev.travelist.model

object TourismData {
    val dummyTourism = listOf(
        Tourism(
            id = 0,
            name = "Gunung Bromo",
            description = "Gunung Bromo atau dalam bahasa Tengger dieja \"Brama\", juga disebut Kaldera Tengger, adalah sebuah gunung berapi aktif di Jawa Timur, Indonesia. Gunung ini memiliki ketinggian 2.329 meter di atas permukaan laut dan berada dalam empat wilayah kabupaten, yakni Kabupaten Probolinggo, Kabupaten Pasuruan, Kabupaten Lumajang, dan Kabupaten Malang. Gunung Bromo terkenal sebagai objek wisata utama di Jawa Timur. Sebagai sebuah objek wisata, Bromo menjadi menarik karena statusnya sebagai gunung berapi yang masih aktif. Gunung Bromo termasuk dalam kawasan Taman Nasional Bromo Tengger Semeru. \nNama Bromo berasal dari nama dewa utama dalam agama Hindu, Brahma. Bentuk tubuh Gunung Bromo bertautan antara lembah dan ngarai dengan kaldera atau lautan pasir seluas sekitar 10 kilometer persegi, Ia mempunyai sebuah kawah dengan garis tengah ± 800 meter (utara-selatan) dan ± 600 meter (timur-barat). Sedangkan daerah bahayanya berupa lingkaran dengan jari-jari 4 km dari pusat kawah Bromo.",
            location = "Malang, Jawa Timur",
            photoUrl = "https://t-2.tstatic.net/tribunnewswiki/foto/bank/images/bromo.jpg",
            rating = 8.9,
       ),
        Tourism(
            id = 1,
            name = "Taman Nasional Wakatobi",
            description = "Taman Nasional Wakatobi di Sulawesi Tenggara merupakan salah satu surga wisata Indonesia yang wajib kamu kunjungi sekali seumur hidup. Kawasan terumbu karang terluas di dunia setelah Great Barrier Reef (Australia) ini memiliki luas 1,4 juta hektare, dengan ribuan spesies flora dan fauna hidup di dalamnya. Tempat wisata menarik di indonesia itu banyak ya rupanya. \nTN Wakatobi adalah salah satu spot menyelam terbaik di dunia. Tak heran kalau ia masuk dalam daftar Situs Warisan Dunia oleh UNESCO pada 2005 silam. Kamu pasti tertarik dong untuk datang ke sini?",
            location = "Wakatobi, Sulawesi Tenggara",
            photoUrl = "https://anekatempatwisata.com/wp-content/uploads/2020/01/Pantai-kepulauan-wakatobi-1-1024x685.jpg",
            rating = 9.4,
        ),
        Tourism(
            id = 3,
            name = "Raja Ampat",
            description = "Kabupaten Raja Ampat adalah salah satu kabupaten di provinsi Papua Barat, Indonesia. Ibukota kabupaten ini terletak di Waisai. Kabupaten ini memiliki 610 pulau, termasuk kepulauan Raja Ampat. Empat di antaranya, yakni Pulau Misool, Salawati, Batanta dan Waigeo, merupakan pulau-pulau besar. Dari seluruh pulau hanya 35 pulau yang berpenghuni sedangkan pulau lainnya tidak berpenghuni dan sebagian besar belum memiliki nama. Kabupaten ini memiliki total luas 67.379,60 km² dengan rincian luas daratan 7.559,60 km² dan luas lautan 59.820,00 km²",
            location = "Papua Barat",
            photoUrl = "https://www.indonesia.travel/content/dam/indtravelrevamp/en/destinations/revisi-2020/destinations-thumbnail/Raja-Ampat-Thumbnail.png",
            rating = 9.8,
        ),
        Tourism(
            id = 4,
            name = "Pantai Kuta",
            description = "Bagi yang berlibur ke Bali, maka yang akan terlintas pertama kali dalam benak adalah Pantai Kuta. Rasanya belum berkunjung ke pulau ini jika belum menginjakkan kaki di atas hamparan pasir putihnya.\nTernyata sejak dekade 1970-an, Pantai Kuta telah menjadi destinasi wisata andalan bagi Pulau Bali. Namun siapa sangka kalau sejak saat itu, pantai ini masih menjadi primadona dengan pesona yang tak pernah pudar. \nBukan hanya diminati oleh wisatawan domestik, turis mancanegara pun berlomba-lomba menikmati keindahan pantai yang berada di sisi selatan Kota Denpasar ini. Tentu saja karena pantai ini memang menawarkan keindahan pasir putih yang memanjang dan luas. Ombak yang cukup tenang bagi peselancar semakin mendukung keseruan.",
            location = "Badung, Bali",
            photoUrl = "https://i2.wp.com/blog.tripcetera.com/id/wp-content/uploads/2020/03/leebudihart_76864081_2484833498431751_3194446755026370817_n-1080x508.jpg",
            rating = 9.6,
        ),
        Tourism(
            id = 5,
            name = "Danau Toba",
            description = "Danau Toba adalah danau alami berukuran besar di Indonesia yang berada di kaldera Gunung Supervulkan. Danau ini memiliki panjang 100 kilometer (62 mil), lebar 30 kilometer (19 mi), dan kedalaman 508 meter (1.667 ft). Danau ini terletak di tengah pulau Sumatra bagian utara dengan ketinggian permukaan sekitar 900 meter (2.953 ft).",
            location = "Toba, Sumatera Utara",
            photoUrl = "https://pict.sindonews.net/dyn/850/pena/news/2021/10/26/156/580390/danau-toba-destinasi-wisata-super-prioritas-dengan-potensi-alam-dan-keunikan-budaya-nuc.jpg",
            rating = 9.4,
        ),
        Tourism(
            id = 6,
            name = "Gunung Prau",
            description = "Gunung Prau merupakan salah satu gunung di Jawa Tengah yang memiliki ketinggian 2.590 meter dari permukaan laut (mdpl). Sejak 4 September 2021, gunung yang masuk dalam wilayah Kabupaten Batang, Kendal, Temanggung, dan Wonosobo sudah membuka kembali seluruh jalurnya setelah tutup akibat PPKM Jawa-Bali. Adapun, jalur pendakian Gunung Prau adalah via Dieng, Patak Banteng, Kalilembu, Igirmranak, Dwarawati, dan Wates. Artikel ini telah tayang di Kompas.com dengan judul",
            location = "Dieng, Wonosobo",
            photoUrl = "https://www.pinhome.id/info-area/wp-content/uploads/2022/07/Gunung-Prau-1.jpg",
            rating = 8.6,
        ),
        Tourism(
            id = 7,
            name = "Gunung Semeru",
            description = "Gunung Semeru atau Gunung Meru adalah sebuah gunung berapi kerucut di Jawa Timur, Indonesia. Gunung Semeru merupakan gunung tertinggi di Pulau Jawa, dengan puncaknya Mahameru, 3.676 meter dari permukaan laut (mdpl). Gunung ini terbentuk akibat subduksi Lempeng Indo-Australia kebawah Lempeng Eurasia. Gunung Semeru juga merupakan gunung berapi tertinggi ketiga di Indonesia setelah Gunung Kerinci di Sumatra dan Gunung Rinjani di Nusa Tenggara Barat.[2] Kawah di puncak Gunung Semeru dikenal dengan nama Jonggring Saloko.",
            location = "Malang, Jawa Timur",
            photoUrl = "https://s3.theasianparent.com/cdn-cgi/image/height=250/tap-assets-prod/wp-content/uploads/sites/24/2022/01/cerita-legenda-gunung-semeru-lead.jpg",
            rating = 9.5,
        ),
        Tourism(
            id = 8,
            name = "Puncak Sikunir",
            description = "Jika Anda berkunjung ke Wonosobo, tidak ada salahnya hampir ke puncak bukit Sikunir untuk berburu golden sunrise dan menikmati pemandangan dari atas ketinggian.\nLokasi bukit Sikunir tepatnya terletak di Desa Sambungan di wilayah Kecamatan Sejajar, Kabupaten Wonosobo, Jawa Tengah. Destinasi yang banyak dikunjungi para penyuka suasana alam ini terletak 2.300 meter dari permukaan laut, sehingga disebut desa tertinggi di pulau Jawa.\nWarga setempat  sebagian besar bekerja sebagai petani kentang, carica dan sayuran lainnya. Lahan pertanian tersebut berada di daerah perbukitan menyerupai hamparan berbentuk terasering. Pemandangan ini tentu memberikan kesan dan pengalaman yang tidak terlupakan bagi yang melintasi.\nKeberadaan Telaga Cebong letaknya tidak jauh dari pemukiman penduduk Desa Sembungan memberikan manfaat bagi kehidupan masyarakat sekitar terutama pertanian.",
            location = "Dieng, Wonosobo",
            photoUrl = "https://asset.kompas.com/crops/NCAQMm6oRt-73HTsM3dqOofSzzI=/0x0:780x390/780x390/data/photo/2014/12/29/0917031sunrisee1780x390.jpg",
            rating = 9.3,
        ),
        Tourism(
            id = 9,
            name = "Pulau Derawan",
            description = "Bagi anda yang hobi travelling, Pulau Derawan menjadi salah satu tujuan wisata yang patut untuk disinggahi. Destinasi menarik ini terletak di Provinsi Kalimantan Timur. Letaknya yang jauh dari kehidupan kota membuatnya cocok sebagai tempat untuk melepaskan penat.\nDi Pulau cantik ini Anda bisa menikmati wisata pantai yang menawan dan mempesona. Sebagai daerah kepulauan yang menyimpan banyak pesona indah, wisata bahari ini juga dikelilingi gugusan pulau yang tak kalah memukau. Alam yang menakjubkan dan udara yang masih sejuk menjadi daya tarik yang ditawarkan oleh pulau indah ini.\nPulau Derawan juga menawarkan panorama bahari yang eksotis dengan biota laut unik yang cukup langka. Dengan kekayaan alam yang masih asri dan terjaga, pulau ini patut dijuluki sebagai surga tersembunyi yang tentunya wajib untuk dikunjungi.",
            location = "Kalimantan Timur",
            photoUrl = "https://www.itrip.id/wp-content/uploads/2020/11/Pulau-Derawan.jpg",
            rating = 9.4,
        ),
        Tourism(
            id = 10,
            name = "Danau Kelimutu",
            description = "esona keindahan danau kelimutu ende dan Hal Unik serta Menarik lain di-sekitarnya Gunung Kelimutu.\nTiwu atau Danau Kelimutu di bagi atas tiga bagian yang sesuai dengan warna – warna air danau yang terdapat didalamnya.Danau Kelimutu terdapat di provinsi? Tepatnya Pulau Flores Provinsi Nusa Tenggara Timur.",
            location = "Flores, Nusa Tenggara Timur",
            photoUrl = "https://cdn.nativeindonesia.com/foto/danau-kelimutu/Menikmati-Keindahan-Danau-Kelimutu.jpeg",
            rating = 8.7,
        ),
        Tourism(
            id = 11,
            name = "Pulau Bunaken",
            description = "Bunaken adalah sebuah pulau seluas 8,08 km² di Teluk Manado, yang terletak di utara pulau Sulawesi, Indonesia. Pulau ini merupakan bagian dari kota Manado, ibu kota provinsi Sulawesi Utara, Indonesia. Pulau Bunaken dapat di tempuh dengan kapal cepat (speed boat) atau kapal sewaan dengan perjalanan sekitar 30 menit dari pelabuhan kota Manado. Di sekitar pulau Bunaken terdapat taman laut Bunaken yang merupakan bagian dari Taman Nasional Bunaken. Taman laut ini memiliki biodiversitas kelautan salah satu yang tertinggi di dunia. Selam scuba menarik banyak pengunjung ke pulau ini. Secara keseluruhan taman laut Bunaken meliputi area seluas 75.265 hektare dengan lima pulau yang berada di dalamnya, yakni Pulau Manado Tua (Manarauw), Pulau Bunaken, Pulau Siladen, Pulau Mantehage berikut beberapa anak pulaunya, dan Pulau Naen. Meskipun meliputi area 75.265 hektare, lokasi penyelaman (diving) hanya terbatas di masing-masing pantai yang mengelilingi kelima pulau itu.",
            location = "Sulawesi",
            photoUrl = "https://www.gocelebes.com/wp-content/uploads/2013/01/keindahan-taman-laut-bunakan.jpg",
            rating = 8.7,
        ),
        Tourism(
            id = 12,
            name = "Danau Ranau",
            description = "Danau Ranau adalah danau terbesar kedua di Sumatra setelah Danau Toba. Danau ini terletak di perbatasan Kabupaten Ogan Komering Ulu Selatan Provinsi Sumatra Selatan dan Kabupaten Lampung Barat Provinsi Lampung. Danau ini tercipta dari gempa besar dan letusan vulkanik dari gunung berapi yang membuat cekungan besar. Secara geografis topografi danau Ranau adalah perbukitan yang berlembah hal ini praktis menjadikan danau Ranau memiliki cuaca yang sejuk. Danau terkenal sering para nelayan untuk mencari ikan seperti mujair, kepor, kepiat, dan harongan.\nTepat di tengah danau terdapat pulau yang bernama Pulau Marisa. Di sana terdapat sumber air panas yang sering digunakan para penduduk setempat ataupun para wisatawan yang datang ke pulau tersebut, terdapat air terjun, dan penginapan. Danau ini juga menjadi objek wisata andalan dari Kabupaten Ogan Komering Ulu Selatan. Di Danau Ranau telah sering diadakan kegiatan Pariwisata dan Olahraga. Diantara kegiatan Motor Traill Adventure bertajuk JASS (Jelajah Alam Serasan Seandanan) dan Touring Road bIke (Sriwijaya Ranau Grand Fondo)",
            location = "OKU Selatan, Sumatera Selatan",
            photoUrl = "https://assets.kompasiana.com/items/album/2021/10/13/img-20191110-052425-616617de3835001c8f0767d4.jpg?t=o&v=770",
            rating = 9.7,
        ),
        Tourism(
            id = 13,
            name = "Gunung Rinjani",
            description = "Gunung Rinjani adalah gunung yang berlokasi di Pulau Lombok, Nusa Tenggara Barat. Gunung yang merupakan gunung berapi kedua tertinggi di Indonesia dengan ketinggian 3.726 mdpl serta terletak pada lintang 8º25' LS dan 116º28' BT ini merupakan gunung favorit bagi pendaki Indonesia karena keindahan pemandangannya.[2] Gunung ini merupakan bagian dari Taman Nasional Gunung Rinjani yang memiliki luas sekitar 41.330 ha dan ini akan diusulkan penambahannya sehingga menjadi 76.000 ha ke arah barat dan timur.\nSecara administratif gunung ini berada dalam wilayah tiga kabupaten: Lombok Timur, Lombok Tengah, dan Lombok Utara.",
            location = "Lombok, Nusa Tenggara Barat",
            photoUrl = "https://media.istockphoto.com/photos/panorama-view-of-mountain-rinjani-of-indonesia-picture-id591992956?b=1&k=20&m=591992956&s=170667a&w=0&h=gvlY7cpoqslw3rOhts9dk6cIKlKLkFecaroZYrkXuBQ=",
            rating = 9.7,
        ),
        Tourism(
            id = 14,
            name = "Danau Sentani",
            description = "Keindahan alam di Papua memang nggak ada matinya. Bukan hanya pantai, melainkan danau-danaunya juga kudu banget untuk dikunjungi, salah satunya Danau Sentani. Nama Sentani mempunya arti, ‘Di sini kami tinggal dengan damai’. Nama itu diberikan oleh seorang pendeta di tahun 1898.\nDanau Sentani juga memiliki sejarah sendiri. Zaman dulu, beberapa penduduk purba dari wilayah Papua Nugini melakukan perjalanan panjang dengan mengendarai seekor naga. Mereka mencari wilayah baru untuk ditempati dan ingin menetap di sana. Namun, naga yang dikendarai nggak mampu terbang lebih jauh, hingga akhirnya jatuh melesat ke sebuah danau tersebut dan naga itu mati terendam di danau. Namun, beberapa penunggang naga selamat dan terjebak di atas bagian tubuh naga yang menyembul keluar dari permukaan danau. Kemudian mereka terdampar di danau tersebut dan tinggal di tubuh naga yang mati. Menurut cerita yang beredar, kepala naga menjadi pulau di sisi timur danau, bagian ekornya menjadi pulau di sisi barat, dan tubuh menjadi pulau di bagian tengah, dinamakan Pulau Asei.",
            location = "Papua, Indonesia",
            photoUrl = "https://www.pegipegi.com/travel/wp-content/uploads/2018/12/danau-sentani.jpg",
            rating = 9.3,
        ),
        Tourism(
            id = 15,
            name = "Pulau Weh",
            description = "Pulau Weh (atau We) atau dikenal juga dengan Pulau Sabang adalah pulau vulkanik kecil yang terletak di barat laut Pulau Sumatra. Pulau ini pernah terhubung dengan Pulau Sumatra, namun kemudian terpisah oleh laut setelah meletusnya gunung berapi terakhir kali pada zaman Pleistosen. Pulau ini terletak di Laut Andaman. Kota terbesar di Pulau Weh, Sabang, adalah kota yang terletak paling barat di Indonesia.\nPulau ini terkenal dengan ekosistemnya. Pemerintah Indonesia telah menetapkan wilayah sejauh 60 km² dari tepi pulau baik ke dalam maupun ke luar sebagai suaka alam. Hiu bermulut besar dapat ditemukan di pantai pulau ini. Selain itu, pulau ini merupakan satu-satunya habitat katak yang statusnya terancam, Bufo valhallae (genus Bufo). Terumbu karang di sekitar pulau diketahui sebagai habitat berbagai spesies ikan.",
            location = "Sabang, Aceh",
            photoUrl = "https://observerid.com/wp-content/uploads/2018/05/Pulau-Weh.jpg",
            rating = 8.6,
        ),
        Tourism(
            id = 16,
            name = "Pulau Komodo",
            description = "Pulau Komodo adalah sebuah pulau yang terletak di Kepulauan Nusa Tenggara, berada di sebelah timur Pulau Sumbawa, yang dipisahkan oleh Selat Sape. Pulau Komodo dikenal sebagai habitat asli hewan komodo. Pulau ini termasuk salah satu kawasan Taman Nasional Komodo yang dikelola oleh Pemerintah Pusat. \nSecara administratif, pulau ini termasuk wilayah Kabupaten Manggarai Barat, Kecamatan Komodo, Provinsi Nusa Tenggara Timur, Indonesia. Pulau Komodo merupakan ujung paling barat Provinsi Nusa Tenggara Timur, berbatasan dengan Provinsi Nusa Tenggara Barat. \nDi Pulau Komodo, hewan komodo hidup dan berkembang biak dengan baik. Hingga Agustus 2009, di pulau ini terdapat sekitar 1300 ekor komodo. Ditambah dengan pulau lain, seperti Pulau Rinca dan dan Gili Motang, jumlah mereka keseluruhan mencapai sekitar 2500 ekor. Ada pula sekitar 100 ekor komodo di Cagar Alam Wae Wuul di daratan Pulau Flores tapi tidak termasuk wilayah Taman Nasional Komodo.\nSelain komodo, pulau ini juga menyimpan eksotisme flora yang beragam kayu sepang yang oleh warga sekitar digunakan sebagi obat dan bahan pewarna pakaian, pohon nitak ini atau sterculia oblongata di yakini berguna sebagai obat dan bijinya gurih dan enak seperti kacang polong.",
            location = "Manggarai Barat, Nusa Tenggara Timur",
            photoUrl = "https://asset.kompas.com/crops/PszTpgbz949Ix6DouywSbAiu0sQ=/0x0:780x520/780x390/data/photo/2019/09/26/5d8c64544d656.jpg",
            rating = 9.3,
        ),
    )
}